- hosts: localhost
  become_user: root
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - install
        - ssh
    - include_tasks: tasks/core-setup.yml
      tags:
        - install
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - install
    - include_tasks: tasks/dotfiles.yml
      tags:
        - install
        - dotfiles
    - include_tasks: tasks/nvim-setup.yml
      tags:
        - install
    - include_tasks: tasks/brave.yml
      tags:
        - install
    - include_tasks: tasks/productivity.yml
      tags:
        -install

