- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True
  tags:
    - all
- name: Install packages
  apt: name={{item}}
  with_items:
    - wireshark
    - kdenlive
    - screenkey
    - gimp
  tags:
    - all
