- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - all
- name: Install ssh key
  become_user: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - all
- name: Set authorized key took from file
  ansible.posix.authorized_key:
    # user: "{{ lookup('env', 'USER') }}"
    user: root
    state: present
    key: "{{ lookup('file', '/usr/local/bin/.ssh/id_ed25519.pub') }}"
    # key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
