- name: Install ZSH
  apt: name=zsh
  tags:
    - install
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - install
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
- name: Delete .zshrc default file
  ansible.builtin.file:
    state: absent
    path: "{{ lookup('env','HOME') }}/.zshrc"
  tags:
    -install
